### ISSUE TITLE
k\d+temp does not work as CPU sensor

### ISSUE THREAD

**Issue by nobody43** [nobodysu/zabbix-mini-IPMI#51]
```
# sensors -u
radeon-pci-0100
Adapter: PCI adapter
temp1:
  temp1_input: 47.000
  temp1_crit: 120.000
  temp1_crit_hyst: 90.000

k10temp-pci-00c3
Adapter: PCI adapter
temp1:
  temp1_input: 46.500
  temp1_max: 70.000
  temp1_crit: 100.000
  temp1_crit_hyst: 99.000

radeon-pci-0008
Adapter: PCI adapter
temp1:
  temp1_input: 46.000
  temp1_crit: 120.000
  temp1_crit_hyst: 90.000
```
