### ISSUE TITLE
How to solve "No CPUs were found for temperature test (mini-IPMI)"?

### ISSUE THREAD

**Issue by yeroslaviz** [nobodysu/zabbix-mini-IPMI#80]
**Describe the problem**
After following the instructions and adding all the files I'm getting the problem, that no CPUs can be found using the parameters provided. 

The discovery became supported, but I get the message:

```
No CPUs were found for temperature test (mini-IPMI)
```

When testing the installation locally, like described in the repository, this is what I get:

```
# /etc/zabbix/scripts/mini_ipmi_lmsensors.py get 10.33.0.158
{
    "data": []
}

# /etc/zabbix/scripts/mini_ipmi_lmsensors.py getverb 10.33.0.158
...
  Data sent to zabbix sender:


"10.33.0.158" mini.cpu.info[ConfigStatus] "NOGPUS, NOCPUS"
zabbix_sender [607789]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 1; total: 1; seconds spent: 0.000023"}]
Response from "10.33.0.65:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000023"
sent: 1; skipped: 0; total: 1
```

**Provide all outputs described in [Testing](https://github.com/nobodysu/zabbix-mini-IPMI#testing) step**
Serial numbers should be replaced with X_SERIAL_X.

**Please complete the following information:**
 - OS: Ubunru 22.04
 - Zabbix server version: 6.0.8
 - Active or passive check: passive and active check are allowed with agent version 5.0.27
 - Using zabbix proxy:  using no proxy

**Additional context**

```
# cat /sys/class/hwmon/hwmon0/temp1_input
24625
root@supercub017:~# sensors -u
bnxt_en-pci-6301
Adapter: PCI adapter
temp1:
  temp1_input: 70.000

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:
  temp1_input: 24.750
Tccd1:
  temp3_input: 25.000
Tccd3:
  temp5_input: 23.000
Tccd5:
  temp7_input: 24.250
Tccd7:
  temp9_input: 22.750

bnxt_en-pci-6300
Adapter: PCI adapter
temp1:
  temp1_input: 70.000

k10temp-pci-00cb
Adapter: PCI adapter
Tctl:
  temp1_input: 27.500
Tccd1:
  temp3_input: 25.750
Tccd3:
  temp5_input: 26.250
Tccd5:
  temp7_input: 26.500
Tccd7:
  temp9_input: 27.250
```

I also tried to solution you posted in [71](https://github.com/nobody43/zabbix-mini-IPMI/issues/71), but I can't use it on my system, as it doesn't let the agent start.

any Ideas?

thanks

Assa
